### ISSUE TITLE
Sourcing Images and compiling training set 

### ISSUE THREAD

**Issue by Felicity-jt** [SATELLITE-CAPSTONE-18/Capstone-Data-Source#3]
Each one of us will source data for 4 features. The data must be in a standardized form (i.e. 256*256 pixels). All images should be occupied mainly by a dominant feature, and data from the same feature should very much look the same. For simplicity, data can be sourced from the available datasets online or google maps, they do not have to be within India for now.

16 features:
1. Industrial
2. Airport
3. Carpark
4. High-density residential areas 1 (non-overlapping)
5. High-density residential areas 2 (overlapping roofs)
6. Medium-density residential areas
7. Low-density residential areas
8. Slums
9. Greenery
10. Cricket ground (green)
11. Cricket ground (brown)
12. Construction
13. Cemetery
14. Agriculture
15. Swimming pool/ golf field/ etc
16. Schools (field)

**Comment by joelowj** [comment]
Just a reminder that, it would be good to keep track of a list of data sets and good research paper. Share it with one another on the main chat. I will include a section on the README.md, under that section will include the list of research paper and a list of datasets which we have explored, so that there won't be any overlapping of work.

**Comment by Felicity-jt** [comment]
In today's meeting, we have agreed on a methodology and concluded a possible path to approach the problem.

1. Use median household income as the indicator for "affluent regions"
[https://project.wnyc.org/median-income-nation/#4/38.63/-95.89](url)
[http://www.justicemap.org/index.php?gsLayer=income&gfLon=-73.95926147&gfLat=40.77811975&giZoom=17&](url)

For reasoning purpose, we will compare the household income and property price for the same region and compute/eye bow the correlation. As they are positively correlated (need to justify further by stats), we represent the affluent level of a region using household income confidently.

2. Focus on US, zoom in from country to state to city level. For states with a large variation in median household income across regions, we choose the richest and poorest cities (2 per state) in these states. Then we crop images of the entire city satellite images to prepare our data set. The zoom level should be 50 meters. In total, we need to prepare 10,000 images. All images from the rich cities will be labeled as "affluent" and vice versa.

3. The model should be trained using such images and labels from developed countries. Further model adjustment for India in specific will be tuned after the testing.

4. The data collection will be done using Joel's code, data sourcing team should use coordinates/grid/stepwise cropping to get images.

**Comment by joelowj** [comment]
Good work guys! (:
I will commit the code and update you guys again.
